---
title: "Clase 8 - Taller de econometría aplicada"
author: "Rafael Sandoval"
date: "24/02/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

packages <- c("tidyverse",
              "haven",
              "magrittr",
              "kableExtra",
              "knitr",
              "MatchIt",
              "ggplot2",
              "stargazer")

installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}
lapply(packages, 
       library, 
       character.only = TRUE)

```

## 1. Límites de Horowitz-Manski

```{r,results='asis',echo=FALSE}

filepath <- "C:/Users/rsf94/Google Drive/MAESTRÍA ITAM/2do semestre/taller_econometria/taller_econometria/clase9/ecls.csv"

data <- as.data.frame(read.csv(filepath))


data %>% group_by(catholic) %>%
  dplyr::summarise(n_students = n(),
            mean_math = mean(c5r2mtsc_std),
            std_error = sd(c5r2mtsc_std)/sqrt(n_students)) %>%
  kable()


with(data, t.test(c5r2mtsc_std ~ catholic))


data_cov <- c('race_white','p5hmage','w3income','p5numpla', 'w3momed_hsb')

data %>% group_by(catholic) %>%
  select(one_of(data_cov)) %>%
  dplyr::summarise_all(funs(mean(.,na.rm=T))) %>%
  kable

lapply(data_cov,
       function(v) {t.test(data[,v] ~ data[,'catholic'])})


data <- data %>% mutate(w3income_1k = w3income/1000)

m_ps <- glm(catholic ~ race_white + w3income_1k +
              p5hmage + p5numpla + w3momed_hsb,
            family=binomial(),data=data)

summary(m_ps)
stargazer(m_ps,type='text')

prs_df <- data.frame(pr_score=predict(m_ps,type='response'),
                     catholic = m_ps$model$catholic)

head(prs_df)

labs <- paste("Actual school type attended:",
c("Catholic", "Public"))

prs_df %>%
mutate(catholic=ifelse(catholic==1,labs[1],labs[2])) %>%
ggplot(aes(x = pr_score)) +
geom_histogram(color = "white") +
facet_wrap(~catholic) +
xlab("Probability of going to Catholic school") +
theme_bw()

data_nomiss <- data %>%
  select(c5r2mtsc,catholic,one_of(data_cov)) %>%
  na.omit()

mod_match <- matchit(catholic ~ race_white + w3income +
                       p5hmage + p5numpla + w3momed_hsb,
                     method="nearest", data=data_nomiss)

dta_m <- match.data(mod_match)
dim(dta_m)
head(dta_m)

plot(mod_match)

```
